[project]
name = "connecpy-conformance"
version = "0.1.0"

dependencies = [
    "brotli",
    "connecpy",
    "httpx[http2]",
    "hypercorn",
    "pytest",
    "pytest-asyncio",
    "uvloop",
    "zstandard",
]

[tool.ruff]
extend = "../pyproject.toml"
